# Site settings
title: HUB
subtitle: Celebrating Human Minds
description: >-
    Personal site for collaborative learning.
author: pmixer
email: PeterHuang2015 dot outlook dot com
baseurl: "/jekyll-theme-prologue"
timezone: Asia/Shanghai
url: "http://talkwithme.cn/"

# be social
github_url:  https://github.com/peterhuang2015
linkedin_url: https://www.linkedin.com/in/pmixer/
twitter_url: https://twitter.com/PeterHuang2015
encoding: UTF-8

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
avatar: profile.png

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
