# Site settings
title: 杂鱼记事
# email:
# description: ""
baseurl: ""
timezone: Asia/Shanghai
url: "http://talkwithme.cn/"
# twitter_username: none
github_username:  PeterHuang2015

encoding: UTF-8

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
avatar: profile.png
author: "黄焖鸡"
